spring:
  application:
    name: springboot-crud-postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      schema: user_db_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_db_schema
      connection-timeout: 10000
  jpa:
    open-in-view: false
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    dsd.springboot_crud_postgresql: DEBUG

server:
  port: 8181
